# Generated by Django 3.1.4 on 2021-01-26 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lenta', '0002_auto_20210126_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
