# Generated by Django 3.1.4 on 2021-02-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenta', '0006_auto_20210204_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comment',
            name='text',
            field=models.CharField(max_length=200, verbose_name='text'),
        ),
    ]
