# Generated by Django 3.1.4 on 2021-02-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenta', '0007_auto_20210204_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comment',
            name='text',
            field=models.TextField(),
        ),
    ]
