# Generated by Django 3.1.4 on 2021-02-04 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lenta', '0008_auto_20210204_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comment',
            name='post',
            field=models.ForeignKey(default=False, null='', on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='lenta.post'),
            preserve_default=False,
        ),
    ]
