# Generated by Django 3.1.4 on 2021-02-04 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lenta', '0009_auto_20210204_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post_comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='lenta.post'),
        ),
        migrations.AlterField(
            model_name='post_comment',
            name='text',
            field=models.CharField(max_length=200, verbose_name='text'),
        ),
    ]
