# Generated by Django 3.1.4 on 2021-02-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0002_auto_20210208_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cast',
            old_name='serial',
            new_name='serials',
        ),
    ]
